# Generated by Django 3.0.5 on 2021-04-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20210403_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list',
            new_name='n_list',
        ),
    ]
