# Generated by Django 3.0.5 on 2021-04-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20210403_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='n_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
    ]
