# Generated by Django 3.0.5 on 2021-04-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20210403_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='n_list',
            new_name='list',
        ),
    ]
